### ISSUE TITLE
Compare 모드에서 Save, SaveAs 버튼 누르면 버튼 Enable 설정

### ISSUE THREAD

**Issue by yoosunnam** [gfsusan/simple-merge#35]
현재 Compare 모드에서 Save, SaveAs 버튼 누르면 
View와 Edit가 Enable되고, 
Save와 SaveAs는 Disable됨!!

-> Compare 모드에서 Save, SaveAs 눌렀을 때
View와 Edit는 Disable,
Save와 SaveAs는 Enable 하도록 바꿔야함!!

**Comment by engyengKim** [comment]
view는 load버튼 말하는거야?

**Comment by yoosunnam** [comment]
마쟝!! Load버튼이얌.
고쳤넹ㅎㅎ 고마워~~~
