### ISSUE TITLE
TEM에 diffIndices 받아 와서 Compare모드에서 Index 표시할 때 사용할수 있게 하기

### ISSUE THREAD

**Issue by gfsusan** [gfsusan/simple-merge#44]

**Comment by yoosunnam** [comment]
Idea 1)
diffIndices에 같은건 0, 빼진 건 1, 더해진 건 2 (Enum)으로 ArrayList(Merge가 보냄)를 받으면
TextEditorModel이 더해진 Indices, 빠진 Indices 각각 ArrayList로 만들어서 CompareTable로 전달

오른쪽 패널을 기준으로
더해진 건 : 왼쪽에 없는 오른쪽에 추가된 내용이 색칠됨 (초록색)
빠진 건 :  왼쪽에 삭제된 부분이 색칠됨(빨간색)
바뀐 건 : 왼쪽은 (빨간색) 오른쪽은 (초록색)

**Comment by gfsusan** [comment]
199433079d87c193d08048faa3a78be3db743771
